image: node:8.11.4

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install
          - npm run tslint
          - npm test
  branches:
    staging:
      - step:
          script:
            - npm install -g npm
            - npm ci || npm install
            - npm test
            - npm i -g pm2
            - pm2 deploy ecosystem.config.js production
