export const enum ErrorCode {
  USER_CREATE_MISSING_CREDINTIALS,
  USER_CREATE_MISSING_FIRSTNAME,
  USER_CREATE_MISSING_LASTNAME,
  USER_CREATE_MISSING_EMAIL,
  USER_CREATE_MISSING_PASSWORD,
  USER_CREATE_EMAIL_EXIST,
  USER_RUD_MISSING_ID, // RUD: Read, Update, Delete
  USER_NOT_FOUND,
  REQUEST_UNAUTHORIZED,
  AUTH_LOGIN_MISSING_EMAIL,
  AUTH_LOGIN_MISSING_PASSWORD,
  NOT_IN_SESSION,
  PASSWORD_NOT_MATCH,
}
